image:
  repository: ghcr.io/stubbi/hermes-operator
  tag: ""
  pullPolicy: IfNotPresent

logLevel: info

createRBAC: true

watchNamespaces: []

metrics:
  secure: true

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

webhook:
  enabled: true
  port: 9443
  certManager:
    enabled: true
    issuerKind: Issuer
    issuerName: hermes-operator-selfsigned
  caBundle: ""
  servingCertSecretName: hermes-operator-webhook-server-cert
